## 제 1유형

In [ ]:
# 아래의 리스트에 대해서 최종결과값을 출력하시오.

data = [10,11,11.2,13,15.5,18,19.8,20,31,33,39.5,42]

# 제 1사분위수와 제 3사분위수를 구하시오.
import numpy as np
Q1 = np.quantile(data,0.25)
Q3 = np.quantile(data,0.75)

In [ ]:
# 제 1사분위수와 제 3사분위수의 차이의 절댓값을 구하시오.
abs(Q1-Q3)

np.float64(18.95)

In [ ]:
# 그 값을 정수로 출력하시오(내림)
abs(Q1-Q3)

np.float64(18.95)

In [ ]:
# 주어진 facebook 데이터셋은 페이스북 라이브에 대한 사용자 반응을 집계한 것이다. 이 중 love반응과 wow반응은 매우 긍정적인 반응이라고 정의할 때
# 전체 반응 수 중 매우 긍정적인 반응 수가 차지하는 비율을 계산하시오. 그리고 그 비율이 0.4 보다 크고 0.5보다 작으며
# 유형이 비디오에 해당하는 경우 정수로 출력하시오

import pandas as pd
facebook_data = pd.read_csv("https://raw.githubusercontent.com/YoungjinBD/dataset/main/facebook.csv")
facebook_data

,status_id,status_type,num_reactions,num_comments,num_shares,num_likes,num_loves,num_wows,num_hahas,num_sads,num_angrys
0,246675545449582_1649696485147474,video,529,512,262,432,92,3,1,1,0
1,246675545449582_1649426988507757,photo,150,0,0,150,0,0,0,0,0
2,246675545449582_1648730588577397,video,227,236,57,204,21,1,1,0,0
3,246675545449582_1648576705259452,photo,111,0,0,111,0,0,0,0,0
4,246675545449582_1645700502213739,photo,213,0,0,204,9,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
7045,1050855161656896_1061863470556065,photo,89,0,0,89,0,0,0,0,0
7046,1050855161656896_1061334757275603,photo,16,0,0,14,1,0,1,0,0
7047,1050855161656896_1060126464063099,photo,2,0,0,1,1,0,0,0,0
7048,1050855161656896_1058663487542730,photo,351,12,22,349,2,0,0,0,0
7049,1050855161656896_1050858841656528,photo,17,0,0,17,0,0,0,0,0

In [ ]:
facebook_data['good_count'] = facebook_data.iloc[:,6:8].sum(axis=1)/facebook_data['num_reactions']

In [ ]:
cond = (
    (facebook_data['status_type'] == 'video') &
    (facebook_data['good_count'] > 0.4) &
    (facebook_data['good_count'] < 0.5)
)

filter = facebook_data[cond]
filter

,status_id,status_type,num_reactions,num_comments,num_shares,num_likes,num_loves,num_wows,num_hahas,num_sads,num_angrys,good_count
3116,134115277150304_226952507866580,video,255,926,181,142,108,0,5,0,0,0.423529
4624,725980084255106_838993039620476,video,1397,771,695,765,485,139,4,1,3,0.446671
4776,614855718638584_852682288189258,video,259,695,263,151,106,0,2,0,0,0.409266
4793,614855718638584_851581351632685,video,146,303,221,73,69,2,1,0,1,0.486301
4812,614855718638584_850456998411787,video,184,530,224,101,80,0,1,1,1,0.434783
...,...,...,...,...,...,...,...,...,...,...,...,...
6308,1050855161656896_1633473383395068,video,416,5352,580,204,194,3,13,1,1,0.473558
6311,1050855161656896_1630620870346986,video,370,6316,633,182,166,2,17,3,0,0.454054
6335,1050855161656896_1616943501714723,video,236,5237,526,138,97,1,0,0,0,0.415254
6371,1050855161656896_1598796110196129,video,239,2574,419,140,95,1,2,1,0,0.401674
6701,1050855161656896_1422444124497996,video,517,5514,388,243,220,8,43,3,0,0.441006

In [ ]:
# netflix 데이터셋은 넷플릭스에 등록된 컨텐츠의 메타데이터이다. 2018년 1월 넷플릭스에 등록된 컨텐츠 중에서 'United Kingdom'이 단독 제작한 컨텐츠의 수를 정수로 출력하시오.

net_data = pd.read_csv("https://raw.githubusercontent.com/YoungjinBD/dataset/main/netflix.csv")

In [ ]:
net_data

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [ ]:
data = net_data[net_data['country']=='United Kingdom']
data

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
32,s33,TV Show,Sex Education,NaN,"Asa Butterfield, Gillian Anderson, Ncuti Gatwa...",United Kingdom,"September 17, 2021",2020,TV-MA,3 Seasons,"British TV Shows, International TV Shows, TV C...",Insecure Otis has all the answers when it come...
65,s66,TV Show,Numberblocks,NaN,"Beth Chalmers, David Holt, Marcel McCalla, Ter...",United Kingdom,"September 15, 2021",2021,TV-Y,6 Seasons,Kids' TV,"In a place called Numberland, math adds up to ..."
72,s73,TV Show,Jack Whitehall: Travels with My Father,NaN,"Jack Whitehall, Michael Whitehall",United Kingdom,"September 14, 2021",2021,TV-MA,5 Seasons,"British TV Shows, Docuseries, International TV...",Jovial comic Jack Whitehall invites his stuffy...
98,s99,TV Show,Octonauts: Above & Beyond,NaN,"Antonio Aakeel, Chipo Chung, Simon Foster, Ter...",United Kingdom,"September 7, 2021",2021,TV-Y,1 Season,"British TV Shows, Kids' TV",The Octonauts expand their exploration beyond ...
...,...,...,...,...,...,...,...,...,...,...,...,...
8740,s8741,TV Show,Wild Alaska,NaN,Dougray Scott,United Kingdom,"March 31, 2017",2015,TV-PG,1 Season,"British TV Shows, Docuseries, Science & Nature TV",The natural bounty of Alaska sustains its dive...
8741,s8742,TV Show,Wild Arabia,NaN,Alexander Siddig,United Kingdom,"March 31, 2017",2013,TV-PG,1 Season,"British TV Shows, Docuseries, Science & Nature TV",The widely varied geology and dramatic landsca...
8744,s8745,Movie,Williams,Morgan Matthews,NaN,United Kingdom,"November 4, 2017",2017,TV-MA,105 min,"Documentaries, International Movies, Sports Mo...",This inspiring documentary charts the birth of...
8758,s8759,TV Show,World's Busiest Cities,NaN,"Anita Rani, Ade Adepitan, Dan Snow",United Kingdom,"February 1, 2019",2017,TV-PG,1 Season,"British TV Shows, Docuseries","From Moscow to Mexico City, three BBC journali..."
8786,s8787,Movie,You Can Tutu,James Brown,"Lily O'Regan, Jeannettsy Enriquez Borges, Joel...",United Kingdom,"December 31, 2017",2017,TV-G,87 min,Children & Family Movies,A gifted young ballet dancer struggles to find...

In [ ]:
data['date'] = pd.to_datetime(net_data['date_added'].str.strip())

<ipython-input-25-3030226526>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['date'] = pd.to_datetime(net_data['date_added'].str.strip())

In [ ]:
data['year_month'] = data['date'].dt.to_period('M')

<ipython-input-26-3014686741>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['year_month'] = data['date'].dt.to_period('M')

In [ ]:
data

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,date,year_month
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...,2021-09-24,2021-09
32,s33,TV Show,Sex Education,NaN,"Asa Butterfield, Gillian Anderson, Ncuti Gatwa...",United Kingdom,"September 17, 2021",2020,TV-MA,3 Seasons,"British TV Shows, International TV Shows, TV C...",Insecure Otis has all the answers when it come...,2021-09-17,2021-09
65,s66,TV Show,Numberblocks,NaN,"Beth Chalmers, David Holt, Marcel McCalla, Ter...",United Kingdom,"September 15, 2021",2021,TV-Y,6 Seasons,Kids' TV,"In a place called Numberland, math adds up to ...",2021-09-15,2021-09
72,s73,TV Show,Jack Whitehall: Travels with My Father,NaN,"Jack Whitehall, Michael Whitehall",United Kingdom,"September 14, 2021",2021,TV-MA,5 Seasons,"British TV Shows, Docuseries, International TV...",Jovial comic Jack Whitehall invites his stuffy...,2021-09-14,2021-09
98,s99,TV Show,Octonauts: Above & Beyond,NaN,"Antonio Aakeel, Chipo Chung, Simon Foster, Ter...",United Kingdom,"September 7, 2021",2021,TV-Y,1 Season,"British TV Shows, Kids' TV",The Octonauts expand their exploration beyond ...,2021-09-07,2021-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8740,s8741,TV Show,Wild Alaska,NaN,Dougray Scott,United Kingdom,"March 31, 2017",2015,TV-PG,1 Season,"British TV Shows, Docuseries, Science & Nature TV",The natural bounty of Alaska sustains its dive...,2017-03-31,2017-03
8741,s8742,TV Show,Wild Arabia,NaN,Alexander Siddig,United Kingdom,"March 31, 2017",2013,TV-PG,1 Season,"British TV Shows, Docuseries, Science & Nature TV",The widely varied geology and dramatic landsca...,2017-03-31,2017-03
8744,s8745,Movie,Williams,Morgan Matthews,NaN,United Kingdom,"November 4, 2017",2017,TV-MA,105 min,"Documentaries, International Movies, Sports Mo...",This inspiring documentary charts the birth of...,2017-11-04,2017-11
8758,s8759,TV Show,World's Busiest Cities,NaN,"Anita Rani, Ade Adepitan, Dan Snow",United Kingdom,"February 1, 2019",2017,TV-PG,1 Season,"British TV Shows, Docuseries","From Moscow to Mexico City, three BBC journali...",2019-02-01,2019-02
8786,s8787,Movie,You Can Tutu,James Brown,"Lily O'Regan, Jeannettsy Enriquez Borges, Joel...",United Kingdom,"December 31, 2017",2017,TV-G,87 min,Children & Family Movies,A gifted young ballet dancer struggles to find...,2017-12-31,2017-12

In [ ]:
d = data.groupby('year_month')['country'].count()
d

year_month
2015-04    1
2015-06    1
2015-10    1
2016-03    3
2016-04    1
          ..
2021-05    3
2021-06    5
2021-07    8
2021-08    3
2021-09    5
Freq: M, Name: country, Length: 69, dtype: int64

In [ ]:
d[d.index == '2018-01']

year_month
2018-01    6
Freq: M, Name: country, dtype: int64

## 제 2유형

Customer_Segmentation 데이터 셋은 고객 세분화 정보를 담고있다.주어진 훈련셋을 활용하여 고객이 속한 세그멘트를 예측하고 해당 예측결과를 다음과 같은 형식의 CSV파일로 저장하시오.

In [1]:
import pandas as pd
customer_data_y = pd.read_csv("https://raw.githubusercontent.com/YoungjinBD/dataset/main/CS_Seg_y_train.csv")

from sklearn.preprocessing import LabelEncoder
scaler = LabelEncoder()
customer_data_y['Segmentation'] = scaler.fit_transform(customer_data_y['Segmentation'])

customer_data_y.drop(columns=['ID'],inplace=True)

In [2]:
customer_data_x = pd.read_csv("https://raw.githubusercontent.com/YoungjinBD/dataset/main/CS_Seg_X_train.csv")

# customer_data_x['Ever_Married'] = scaler.fit_transform(customer_data_x['Ever_Married'])
# customer_data_x['Spending_Score'] = scaler.fit_transform(customer_data_x['Spending_Score'])
# customer_data_x['Graduated'] = scaler.fit_transform(customer_data_x['Graduated'])
# customer_data_x['Gender'] = scaler.fit_transform(customer_data_x['Gender'])
# customer_data_x = pd.get_dummies(customer_data_x,columns=['Profession'],dtype=int)
customer_data_x.drop(columns=['ID'],inplace=True)
customer_data_x.info()
for col in customer_data_x.select_dtypes('object').columns:
    customer_data_x[col] = customer_data_x[col].astype('category') # xgbooet는 category만 범주형으로 입력해야한다.
customer_data_x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6718 entries, 0 to 6717
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           6718 non-null   object
 1   Ever_Married     6718 non-null   object
 2   Age              6718 non-null   int64
 3   Graduated        6718 non-null   object
 4   Profession       6718 non-null   object
 5   Work_Experience  6718 non-null   float64
 6   Spending_Score   6718 non-null   object
 7   Family_Size      6718 non-null   float64
dtypes: float64(2), int64(1), object(5)
memory usage: 420.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6718 entries, 0 to 6717
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           6718 non-null   category
 1   Ever_Married     6718 non-null   category
 2   Age              6718 non-null   int64
 3   Graduated        6718 non-null   category
 4   Profession       6718 non-null   category
 5   Work_Experience  6718 non-null   float64
 6   Spending_Score   6718 non-null   category
 7   Family_Size      6718 non-null   float64
dtypes: category(5), float64(2), int64(1)
memory usage: 191.2 KB

**상황에 따른 인코딩⭐**

| 모델 종류                                                 | 라벨 인코딩 적합 여부           | 이유                          |
| ----------------------------------------------------- | ---------------------- | --------------------------- |
| 트리 계열 (예: DecisionTree, RandomForest, XGBoost)        | **적합함**                | 숫자의 크기보다는 구분만 중요함           |
| 선형 모델, 회귀모델 (예: LinearRegression, LogisticRegression) | **주의 필요**              | 숫자 간 **서열 관계**를 잘못 학습할 수 있음 |
| 딥러닝 (예: MLP)                                          | 보통 One-Hot Encoding 추천 | 숫자 크기 의미 없음, 분산 고려 필요       |

In [4]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd

# 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(customer_data_x, customer_data_y, test_size=0.2, random_state=42)


# XGBoost 분류기 모델 생성 및 학습
model = xgb.XGBClassifier(enable_categorical=True, num_class = 4, eval_metric='mlogloss')  # 다중 분류
model.fit(X_train, y_train)

# 예측
y_pred = model.predict(X_test)

# 정확도 평가
accuracy = accuracy_score(y_test, y_pred)
print(f"정확도: {accuracy:.2f}")

정확도: 0.49